### ISSUE TITLE
Content repository API is never initialized without a content-repositories.json

### ISSUE THREAD

**Issue by smashwilson** [deconst/strider-deconst-control#13]
The plugin crashes if you don't have a `content-repositories.json` file in your control repo, because it never initializes the content service connection.

```
No content-repositories.json file found.
Skipping control repository build setup.
Submitting assets found at /workspace/data/rackerlabs-nexus-control-56c73207965bd90100b91023.
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Cannot read property 'post' of undefined

TypeError: Cannot read property 'post' of undefined
    at Object.exports.issueAPIKey (/strider/deconst-strider/node_modules/strider-deconst-control/lib/content-service.js:4:22)
    at /strider/deconst-strider/node_modules/strider-deconst-control/lib/prepare.js:102:20
    at /strider/deconst-strider/node_modules/async/lib/async.js:718:13
    at iterate (/strider/deconst-strider/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/strider/deconst-strider/node_modules/async/lib/async.js:281:9)
    at _parallel (/strider/deconst-strider/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/strider/deconst-strider/node_modules/async/lib/async.js:739:9)
    at prepare (/strider/deconst-strider/node_modules/strider-deconst-control/lib/prepare.js:263:9)
    at /strider/deconst-strider/node_modules/strider-deconst-control/lib/prepare.js:65:7
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by smashwilson** [comment]
This was actually taken care of by #25.
